import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "aos/dist/aos.css";
const iranSansXFont = localFont({
 src: [
  {path: "../public/font/IranSansX/IRANSansXFaNum-Thin.woff", weight: "100"},
  {path: "../public/font/IranSansX/IRANSansXFaNum-Light.woff", weight: "300"},
  {path: "../public/font/IranSansX/IRANSansXFaNum-Regular.woff", weight: "400"},
  {path: "../public/font/IranSansX/IRANSansXFaNum-Medium.woff", weight: "500"},
  {path: "../public/font/IranSansX/IRANSansXFaNum-DemiBold.woff", weight: "600"},
  {path: "../public/font/IranSansX/IRANSansXFaNum-Bold.woff", weight: "700"},
  {path: "../public/font/IranSansX/IRANSansXFaNum-ExtraBold.woff", weight: "800"},
  {path: "../public/font/IranSansX/IRANSansXFaNum-Black.woff", weight: "900"},
 ],
 variable: "--font-iranSans",
});

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};
export const viewport = {
 width: "device-width",
 initialScale: 1,
 // maximumScale: 1,
 // userScalable: false,
 // Also supported by less commonly used
 // interactiveWidget: 'resizes-visual',
};
export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="fa" dir="rtl">
   <body
    style={{fontFamily: "var(--font-iranSans), Arial, sans-serif"}}
    className={`${iranSansXFont.variable} font-iranSans leading-loose font-medium text-md text-txtColor bg-WhiteBackground`}
   >
    <>
     <Header />
     {children}
     <Footer />
    </>
   </body>
  </html>
 );
}
